server:
  port: 8001
spring:
  application:
    name: product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/changgou?useUnicode=ture&characterEncoding=UTF-8&serviceTimeZone=UTC
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
